### ISSUE TITLE
500 error when changing authors name on import

### ISSUE THREAD

**Issue by sethryder** [sethryder/modpackindex#12]
If you change the Authors name on an import author it will break the mod import page.

**Comment by sethryder** [comment]
[2015-09-03 23:45:15] 1.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/forge/staging.modpackindex.com/app/controllers/ImportController.php:305
Stack trace:
#0 /home/forge/staging.modpackindex.com/app/controllers/ImportController.php(305): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/forge/sta...', 305, Array)
#1 [internal function]: ImportController->getImportMod('424')
#2 /home/forge/staging.modpackindex.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('getImportMod', Array)
#4 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(ImportController), Object(Illuminate\Routing\Route), 'getImportMod')
#5 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ImportControlle...', 'getImportMod')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('424')
#7 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#8 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(11088): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/forge/staging.modpackindex.com/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 /home/forge/staging.modpackindex.com/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
forge@prod1-modpackindex:~/staging.modpackindex.com/app/storage/logs$

**Comment by helkarakse** [comment]
What steps can I take to reproduce this error? Is there any sample data that I can use for this as well?

**Comment by sethryder** [comment]
Sorry for the lack of response, was a busy weekend and then a few busy days at work. I have a fix ready to go.
