### ISSUE TITLE
sorting by player count on server table doesn't work properly

### ISSUE THREAD

**Issue by sethryder** [sethryder/modpackindex#41]
doesnt sort properly, should sort by current players.

https://www.modpackindex.com/servers

**Comment by helkarakse** [comment]
Seems to be sorting fine to me. http://i.imgur.com/3t9bIZG.png

**Comment by sethryder** [comment]
Hrmm, must depend on the player count on certain servers, because one is out of place for me at the moment:

https://www.dropbox.com/s/07hu9t4dli30qh6/2015-09-06_11-56-04.png?dl=0

**Comment by helkarakse** [comment]
I see it. Its sorting it alphabetically not numerically.
